pipeline:
  name: REPO1 REPO2 Test
  identifier: REPO1_REPO2_Test
  projectIdentifier: Product_Exploratory
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.tejakummarikuntla
        repoName: SBOM-drift-generation-node
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.kubernetes_connector_for_at
              namespace: ssca-at
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: SscaOrchestration
                  name: SscaOrchestration_1
                  identifier: SscaOrchestration_1
                  spec:
                    mode: generation
                    tool:
                      type: Syft
                      spec:
                        format: spdx-json
                    source:
                      type: repository
                      spec:
                        url: https://github.com/tejakummarikuntla/easybuggy-vulnerable-application
                        variant_type: branch
                        variant: main
                    resources:
                      limits:
                        memory: 500Mi
                        cpu: "0.5"
